apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-authors
  labels:
    app: app-authors
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-authors
  template:
    metadata:
      name: app-authors
      labels:
        app: app-authors
    spec:
      containers:
        - name: app-authors
          image: docker.io/aaguamaninga/app-authors-examen:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: JAKARTA_PERSISTENCE_JDBC_URL
              value: "jdbc:postgresql://dbserver:5432/distribuida"  # URL de la base de datos
            - name: JAKARTA_PERSISTENCE_JDBC_USER
              value: "postgres"  # Usuario de la base de datos
            - name: JAKARTA_PERSISTENCE_JDBC_PASSWORD
              value: "postgres"
          livenessProbe:
            httpGet:
              path: /observe/health/live
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /observe/health/ready
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: app-authors-service
  labels:
    app: app-authors
spec:
  type: NodePort
  selector:
    app: app-authors
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---